### ISSUE TITLE
Python3.7: DLL load failed on nanoserver

### ISSUE THREAD

**Issue by tgckpg** [psycopg/psycopg2#1033]
Running into this issue when trying to make a custom docker image.
( using the `psycopg2-binary` package )
```
Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\>set path
Path=C:\PostgreSQL\bin;C:\Windows\system32;C:\Windows;;C:\Program Files\PowerShell;C:\Python;C:\Python\Scripts;
PATHEXT=.COM;.EXE;.BAT;.CMD

C:\>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed: The specified module could not be found.
>>> import ctypes
>>> ctypes.WinDLL('libpq')
<WinDLL 'libpq', handle 180000000 at 0x1a0a1fca4c8>
>>>
```

Note that the `libpq` seems to be there. I can run `psql` just fine. After some googling I also tried to distribute the vcredist
```
C:\Windows\System32>dir msvc*.dll
 Volume in drive C has no label.
 Volume Serial Number is 32B2-31F3

 Directory of C:\Windows\System32

11/28/2019  06:47 PM           560,376 msvcp110_win.dll
11/28/2019  06:47 PM           660,032 msvcp120.dll
01/25/2020  07:22 PM           618,264 msvcp140.dll
01/25/2020  07:25 PM           611,840 msvcp60.dll
11/28/2019  06:47 PM           639,632 msvcp_win.dll
01/25/2020  07:26 PM           829,264 msvcr100.dll
11/28/2019  06:47 PM           946,712 msvcr120.dll
11/28/2019  06:47 PM           637,864 msvcrt.dll
               8 File(s)      5,503,984 bytes
               0 Dir(s)  21,276,901,376 bytes free

```

But still got the same error. What am I missing?

**Comment by dvarrazzo** [comment]
No idea about docker on windows. Please try writing the mailing list to see if you get help there.

**Comment by tgckpg** [comment]
No prob, I fixed it!

I found out I needed this dll for it to work `C:\Windows\System32\shfolder.dll`

Thanks anyway:)

**Comment by RonRadtke** [comment]
@tgckpg I'm facing the same problem right now. How did you install the` shfolder.dll`?

**Comment by tgckpg** [comment]
> 
> 
> @tgckpg I'm facing the same problem right now. How did you install the` shfolder.dll`?
```dockerfile
FROM mcr.microsoft.com/windows/servercore:1903-amd64 as dlls
COPY --from=dlls C:\Windows\System32\shfolder.dll C:\Windows\System32\
```
