### ISSUE TITLE
Add Python 3.9 support

### ISSUE THREAD

**Issue by tharanga2006** [psycopg/psycopg2#1099]
OS : Windows 10 Home  64bit
Python Version : Python 3.9.0a6
Django Version : 3.0.5
Postgress db Version : 12
setting.py  < db entry >

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'xxxx',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost'
    }
}
```

Error  that I'm receiving 

```
(dev-test) F:\Personal\xxxx\Learning\Django\projects\jangoproject\devtest>python manage.py startserver
Traceback (most recent call last):
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\backends\postgresql\base.py", line 25, in <module>
    import psycopg2 as Database
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Personal\xxxx\Learning\Django\projects\jangoproject\devtest\manage.py", line 21, in <module>
    main()
  File "F:\Personal\xxxx\Learning\Django\projects\jangoproject\devtest\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line 
    utility.execute()
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\models\base.py", line 121, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\models\base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\models\options.py", line 208, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\utils.py", line 207, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "c:\users\lenovo\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\LENOVO\Envs\dev-test\lib\site-packages\django\db\backends\postgresql\base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: DLL load failed while importing _psycopg: The specified 
module could not be found.
```

**Comment by dvarrazzo** [comment]
Python 3.9 is not supported yet.

You can try and build the packages by fixing the [`appveyor.yml`](https://github.com/psycopg/psycopg2-wheels/blob/master/appveyor.yml) in the [psycopg2-wheels](https://github.com/psycopg/psycopg2-wheels) and [`scripts/appveyor.py`](https://github.com/psycopg/psycopg2/blob/master/scripts/appveyor.py) in this repo, in ways that should be trivial, but which require python 3.9 to be installed on appveyor

**Comment by dvarrazzo** [comment]
Testing compiling psycopg2 with Python 3.9 works well. Packages will be released after Python release.

**Comment by lathish2232** [comment]
**ImportError: DLL load failed while importing _psycopg: The specified module could not be found in python 3.9**

**Comment by tigerfoot** [comment]
Unfortunately, this has been closed too early, as no new packages have been release after python 3.9 launch.
People under windows who get python 39 by default with chocolatey installation are just now in trouble \o/ ;-)
Would be cool to make a new release with the fix inclued.

**Comment by dvarrazzo** [comment]
@tigerfoot see #1160

**Comment by tigerfoot** [comment]
@dvarrazzo I didn't catch all the fact behind the last comment, before I hit enter and publish the comment. Always the same story when we're in a rush. Sorry for that.
At least you know now that python3 3.9 on Windows chocolatey repository is build with MSVC 2019 ;-)

**Comment by jha7itdhani** [comment]
From the official documentation, it is clear  it should support but seems not yet the case. I am using python 3.10 and also installed the library: psycopg2 but getting the same error:
 **File "C:\Program Files\Python310\lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    _from psycopg2._psycopg import (    # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found._**

[https://www.psycopg.org/docs/install.html#install-from-source](url)

**Comment by dvarrazzo** [comment]
@jha7itdhani As you can see [here](https://pypi.org/project/psycopg2/#files), `psycopg2-2.9.3-cp310-cp310-win_amd64.whl` says that windows Python 3.10 is supported. It is your responsibility to make it work on your machine.

Closing the issue as it is solved and I don't want people to report versions different than python 3.9 on this ticket.
