### ISSUE TITLE
_psycopg.py doesn't exist!

### ISSUE THREAD

**Issue by JackOfSpade** [psycopg/psycopg2#1112]
In the **psycopg2** directory,  `__init__.py`  contains `from psycopg2._psycopg`.  But there is no  `_psycopg..dll` file in the **psycopg2** directory???

So I get error:

```
Failed to get real commands on module "mysite": python process died with code 1: Traceback (most recent call last):
  File "C:\Users\Jack\Anaconda3\envs\mysite\lib\site-packages\django\db\backends\postgresql\base.py", line 25, in <module>
    import psycopg2 as Database
  File "C:\Users\Jack\Anaconda3\envs\mysite\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pycharm\_jb_manage_tasks_provider.py", line 25, in <module>
    django.setup()
  File "C:\Users\Jack\Anaconda3\envs\mysite\lib\site-packages\django\__init__.py", line 24, in setup
```

**Comment by dvarrazzo** [comment]
There should be a ```.so```.

We only support installing psycopg using our installer. If you are using Anaconda open a bug with them.
