### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg2.extras'; 'psycopg2' is not a package

### ISSUE THREAD

**Issue by don1uppa** [psycopg/psycopg2#1116]
Everything works fine until I try to do a unittest.   I tried both psycopg2 and psycopg2-binary as some post suggest.  Thank you for reviewing.

Here is my console output:
```
(venv) C:\edh-data-exporter\src\application\python>pip install psycopg2
Requirement already satisfied: psycopg2 in c:\edh-data-exporter\venv\lib\site-packages (2.8.5)

(venv) C:\edh-data-exporter\src\application\python>python -m unittest discover -s C:/edh-data-exporter/tests -t C:\edh-data-exporter
E
======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "C:\Users\diuppa\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "C:\Users\diuppa\AppData\Local\Programs\Python\Python38-32\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\edh-data-exporter\tests\__init__.py", line 1, in <module>
    from test_exporter import TestExporter
  File "C:\edh-data-exporter\src\application\python\test_exporter.py", line 11, in <module>
    import exporter
  File "C:\edh-data-exporter\src\application\python\exporter.py", line 6, in <module>
    from ack_response_report import AckRespReport
  File "C:\edh-data-exporter\src\application\python\ack_response_report.py", line 3, in <module>
    from psycopg2.extras import NamedTupleConnection
ModuleNotFoundError: No module named 'psycopg2.extras'; 'psycopg2' is not a package


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

(venv) C:\edh-data-exporter\src\application\python>
```

**Comment by dvarrazzo** [comment]
It doesn't seem your psycopg is installed correctly. Uninstall and reinstall it. If you are doing anything strange with your python library directories you are on your own.

**Comment by don1uppa** [comment]
This was a unittest issue.
 I had to add: sys.modules['boto3.session.client.s3'] = Mock()
Took awhile to figure this out.
