### ISSUE TITLE
Statement execution with deferred keyword

### ISSUE THREAD

**Issue by RyanSiu1995** [psycopg/psycopg2#1182]
Hi, I have a problem with executing the following statement with psycopg2 2.8.x and 2.7.x against postgres9.6.
```sql
ALTER TABLE "table1" ADD COLUMN "f_id" integer NULL CONSTRAINT "constraint_a" REFERENCES "table_b"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "constraint_a" IMMEDIATE
```
The errors returned by 2.7.x and 2.8.x are the following respectively.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.ProgrammingError: constraint "constraint_a" does not exist
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.errors.UndefinedObject: constraint "constraint_a" does not exist
```
However, with the exact statement, I could execute without any problem directly with `psql`.
Any idea on this?

**Comment by RyanSiu1995** [comment]
For more information, this is the query generated by the Django 3.x.
I use the Django `AddField` function to generate the corresponding statement for altering the table.
