### ISSUE TITLE
installing 'psycopg2-binary' on mac Big Sur 11.1 M1 - Python 3.9

### ISSUE THREAD

**Issue by ahaffar** [psycopg/psycopg2#1281]
I am running into below error while installing the package via pipenv.
MacOS X 11.1
Apple M1 processor
Python -V 3.9.5 and also tried with 3.8.7 same issue 
```sh
#16 409.4 Installing 'psycopg2-binary'
#16 409.5 $ ['/usr/local/bin/pip', 'install', '--verbose', '--upgrade', '--require-hashes', '--no-use-pep517', '--no-deps', '--exists-action=i', '-r', '/tmp/pipenv-lcvqdjrs-requirements/pipenv-h5kx5keb-requirement.txt', '-i', 'https://pypi.org/simple']
#16 411.6 Traceback (most recent call last):
#16 411.6   File "/usr/local/bin/pipenv", line 8, in <module>
#16 411.6     sys.exit(cli())
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
#16 411.6     return self.main(*args, **kwargs)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 782, in main
#16 411.6     rv = self.invoke(ctx)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
#16 411.6     return _process_result(sub_ctx.command.invoke(sub_ctx))
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
#16 411.6     return ctx.invoke(self.callback, **ctx.params)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
#16 411.6     return callback(*args, **kwargs)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
#16 411.6     return ctx.invoke(f, obj, *args, **kwargs)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
#16 411.6     return callback(*args, **kwargs)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
#16 411.6     return f(get_current_context(), *args, **kwargs)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
#16 411.6     retcode = do_install(
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2052, in do_install
#16 411.6     do_init(
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 1304, in do_init
#16 411.6     do_install_dependencies(
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 899, in do_install_dependencies
#16 411.6     batch_install(
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 796, in batch_install
#16 411.6     _cleanup_procs(procs, failed_deps_queue, retry=retry)
#16 411.6   File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 703, in _cleanup_procs
#16 411.6     raise exceptions.InstallError(c.dep.name, extra=err_lines)
#16 411.6 pipenv.exceptions.InstallError: ERROR: Couldn't install package: pandas
#16 411.6  Package installation failed...
#16 411.7 /usr/local/lib/python3.9/subprocess.py:1052: ResourceWarning: subprocess 1716 is still running
#16 411.7   _warn("subprocess %s is still running" % self.pid,
#16 411.7 sys:1: ResourceWarning: unclosed file <_io.FileIO name=6 mode='wb' closefd=True>
#16 411.7 sys:1: ResourceWarning: unclosed file <_io.FileIO name=7 mode='rb' closefd=True>
------
executor failed running [/bin/sh -c pipenv install --system --deploy --dev --verbose]: exit code: 1
```

**Comment by ahaffar** [comment]
i am facing this while building a docker image, I tried the following as well with no luck 

```sh
brew install libpq --build-from-source

export LDFLAGS="-L/opt/homebrew/opt/libpq/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libpq/include"
export LDFLAGS=“-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

```

**Comment by dvarrazzo** [comment]
"pipenv.exceptions.InstallError: ERROR: Couldn't install package: pandas" is not a psycopg error.
