### ISSUE TITLE
v2.9.1 `libcrypto.1.1.dylib` (which was built for Mac OS X 10.15) fails with MacOS High Sierra 10.13.6 🐛 

### ISSUE THREAD

**Issue by JV-conseil** [psycopg/psycopg2#1301]
**Platform & Version**

- Platform: MacOS High Sierra 10.13.6
- psycopg2-binary: 2.9.1
- Django: 3.2.4
- Python: 3.8.10

**Describe the bug**

```bash
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: ~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/.dylibs/libcrypto.1.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in ~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/.dylibs/libcrypto.1.1.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/models/options.py", line 207, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/utils.py", line 204, in create_connection
    backend = load_backend(db['ENGINE'])
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 29, in <module>
    raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: ~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/.dylibs/libcrypto.1.1.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in ~/.local/share/virtualenvs/SYAMQg7D/lib/python3.8/site-packages/psycopg2/.dylibs/libcrypto.1.1.dylib
```

**To Reproduce**

Not available.

**Temporary Workaround**

Go back to `psycopg2-binary v2.8.6`

```txt
requirements.txt

psycopg2-binary==2.8.6
```

**Comment by dvarrazzo** [comment]
Github Actions only offers MacOS 10.15 workers. If you or anyone else is able to configure the build script to build packages compatible with 10.13 too I'm happy to receive a MR. Otherwise please install psycopg2 from sources.

**Comment by JV-conseil** [comment]
As a workaround, I've adapted my `bash` script to build my local virtual environment with `pipenv`:

```bash

pipenv install --verbose -r ./requirements.txt  # <-- psycopg2-binary>=2.9.1 is installed

# MacOS High Sierra 10.13.6 Hack
if [[ $(sw_vers -productVersion) == "10.13.6" ]]
then
    sw_vers
    pipenv uninstall --verbose --skip-lock "psycopg2-binary>=2.9.1"
    pipenv install --verbose --skip-lock "psycopg2-binary==2.8.6"
fi

pipenv shell python manage.py runserver

```

**Comment by dvarrazzo** [comment]
Just assuming that the two platforms are not binary compatible.
