### ISSUE TITLE
Django tests fail on psycopg2 2.9+

### ISSUE THREAD

**Issue by M1ha-Shvn** [psycopg/psycopg2#1324]
Hi
I use django with psycopg2-binary.
After psycopg2 2.9.0 has been released some of my tests started failing with error:
```
Traceback (most recent call last):
  File "/home/runner/work/django-pg-bulk-update/django-pg-bulk-update/tests/test_bulk_update_or_create.py", line 487, in test_auto_now
    for instance in AutoNowModel.objects.all():
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 844, in results_iter
    for rows in results:
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in cursor_iter
    sentinel):
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1288, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC
```
Here is full build in GitHub Actions of my libarary:
https://github.com/M1ha-Shvn/django-pg-bulk-update/runs/2996460002?check_suite_focus=true

Everything is OK with psycopg 2.8.6.

**Comment by M1ha-Shvn** [comment]
Sorry, found [a duplicate issue](https://github.com/psycopg/psycopg2/issues/1293)
