### ISSUE TITLE
ImportError: DLL load failed while importing _psycopg:

### ISSUE THREAD

**Issue by novonomad** [psycopg/psycopg2#1475]
Attempt to import psycopg2 (v 2.9.3) into Python 3.11.0.b4 results in error.

```
(.env) C:\experimental>py -V
Python 3.11.0b4

(.env) C:\experimental>pip install psycopg2
Collecting psycopg2
  Using cached psycopg2-2.9.3-cp311-cp311-win_amd64.whl
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.3

(.env) C:\experimental>py
Python 3.11.0b4 (main, Jul 11 2022, 15:47:56) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\experimental\.env\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.
>>>
```

**Comment by dvarrazzo** [comment]
Python 3.11 is not supported yet. It works no problem, I have tested it, but the windows binaries are not uploaded yet on pypi, and they won't until Python 3.11 is officially released.

If you want to build psycopg on windows yourself, you are on your own. You can see the complete recipe about how to do it by looking at the Appveyor CI script.

In this case it looks you just have to install postgres in order to find libpq.dll and put it somewhere in your path. However I don't have a windows machine to test.
