### ISSUE TITLE
Support json dtypes

### ISSUE THREAD

**Issue by latot** [psycopg/psycopg2#1542]
Hi, Actually postgres, from years ago support json types, pandas too!, seems the support from psycopg2 is the missed part to put it to work!

```
import pandas

json_data = []

for i in range(10):
  json_data.append({0: i, 1:10})

df = pandas.DataFrame({'a': range(10), 'json': json_data})

with engine.connect() as session:
  df.to_sql("table", session)

Traceback (most recent call last):
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/usr/lib/python3.10/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
psycopg2.ProgrammingError: can't adapt type 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1738, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1335, in insert_records
    raise err
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/pipe/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 853, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/pipe/.local/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
  File "/usr/lib/python3.10/site-packages/psycopg2/extras.py", line 1296, in execute_values
    parts.append(cur.mogrify(template, args))
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO "table" (index, a, json) VALUES (%(index)s, %(a)s, %(json)s)]
[parameters: ({'index': 0, 'a': 0, 'json': {0: 0, 1: 10}}, {'index': 1, 'a': 1, 'json': {0: 1, 1: 10}}, {'index': 2, 'a': 2, 'json': {0: 2, 1: 10}}, {'index': 3, 'a': 3, 'json': {0: 3, 1: 10}}, {'index': 4, 'a': 4, 'json': {0: 4, 1: 10}}, {'index': 5, 'a': 5, 'json': {0: 5, 1: 10}}, {'index': 6, 'a': 6, 'json': {0: 6, 1: 10}}, {'index': 7, 'a': 7, 'json': {0: 7, 1: 10}}, {'index': 8, 'a': 8, 'json': {0: 8, 1: 10}}, {'index': 9, 'a': 9, 'json': {0: 9, 1: 10}})]
```

**Please complete the following information:**
- OS: Gentoo 64
- Psycopg version: 2.9.4
- Python version: 3.10.9
- PostgreSQL version: 15 (latest postgis from docker)
- pip version: 22.3.1

Thx!

**Comment by dvarrazzo** [comment]
Have you seen [this](https://www.psycopg.org/docs/extras.html#adapt-json)? Are you referring to something not covered here?

**Comment by latot** [comment]
Yeah!, seems is covered, in that case..., why is failing pandas? where it comes the error? psycopg2, sqlalchemy or where? I though was here.
