### ISSUE TITLE
psycopg2-postgres DB URL not accepting special characters in the password

### ISSUE THREAD

**Issue by nov301996** [psycopg/psycopg2#1547]
### Discussed in https://github.com/psycopg/psycopg2/discussions/1546

<div type='discussions-op-text'>

<sup>Originally posted by **nov301996** February 16, 2023</sup>
Hello,

       We are using postgresSQL with psycopg2 for setting up the connection DB for MLFlow, In this we are trying to pass the password to the DB_URL with special characters contained in it.  If I am ignoring usage of '_[]:=?' the DB Connection is getting established.

However if we are ignoring '_[]:=?' characters in the password, the DB Connection is being established properly. 

The following is the format of the DB URL :
postgresql+psycopg2://{{userName}:{password}//{{database}}?host={{ip}}&sslmode=verify-ca&sslrootcert={{sslRootCert}}&sslcert={{sslCert}}&sslkey={{sslKey}}

The following is the error on MLFlow application when trying to establish the connection using postgres and psycopg2:

ERROR mlflow.cli: Invalid IPv6 URLTraceback (most recent call last): 
 File "/app/mlflow/cli.py", line 461, in server    initialize_backend_stores(backend_store_uri, registry_store_uri, default_artifact_root) 
 File "/app/mlflow/server/handlers.py", line 267, in initialize_backend_stores    _get_tracking_store(backend_store_uri, default_artifact_root)  
File "/app/mlflow/server/handlers.py", line 246, in _get_tracking_store    _tracking_store = _tracking_store_registry.get_store(store_uri, artifact_root)  
File "/app/mlflow/tracking/_tracking_service/registry.py", line 39, in get_store    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)  
File "/app/mlflow/tracking/_tracking_service/registry.py", line 48, in _get_store_with_resolved_uri    builder = self.get_store_builder(resolved_store_uri)  
File "/app/mlflow/tracking/registry.py", line 73, in get_store_builder    scheme = store_uri if store_uri == "databricks" else get_uri_scheme(store_uri)  
File "/app/mlflow/utils/uri.py", line 166, in get_uri_scheme    scheme = urllib.parse.urlparse(uri_or_path).scheme  
File "/usr/local/lib/python3.7/urllib/parse.py", line 371, in urlparse    splitresult = urlsplit(url, scheme, allow_fragments) 
File "/usr/local/lib/python3.7/urllib/parse.py", line 469, in urlsplit    
raise ValueError("Invalid IPv6 URL")ValueError: Invalid IPv6 URL

If password is XXX1=_[XXXX], can someone please translate on how we need to pass the password to the module. 

Can someone in psycopg2 Community/Contributors please help us resolve this error ? Please let us know how to pass the password along with special characters for which the psycopg2 module accepts ?</div>

**Comment by dvarrazzo** [comment]
Answered in the discussion, not an issue.
