### ISSUE TITLE
aarch64: Server Name Indication (SNI) is not presented on TLS connections

### ISSUE THREAD

**Issue by sjmiller609** [psycopg/psycopg2#1550]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:

Mac OS 13.2 (M1 Pro)

- Psycopg version: psycopg2-binary==2.9.5
```
root@a9f5ff8b64d5:/# pip freeze | grep psy
psycopg2-binary==2.9.5
```
- Python version: Python 3.11.2
```
root@a9f5ff8b64d5:/# python3 --version
Python 3.11.2
```
- PostgreSQL version: 15.2
- pip version: pip 22.3.1 

**Describe the bug**
Please let us know:

1: what you did

I am starting a python container, installing pycopg2-binary, and attempting a connection. I am running a packet capture during the connection attempt. I tried this on both linux/amd64 and linux/arm64. On amd64 it is working and on arm64 it is having an error.

I can see in the packet capture on amd64, it will include **Server Name Indication in the Client Hello of the TLS handshake**. SNI was introduced in postgres 14: https://www.postgresql.org/docs/release/14.0/

On AMD64: (working)

```
➜  ~ docker run -it --rm --platform=linux/amd64 python:3.11 /bin/bash
root@bdf56fa283aa:/# pip install  psycopg2-binary
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 11.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
root@bdf56fa283aa:/# python
iPython 3.11.2 (main, Feb 11 2023, 02:24:27) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  psycopg2
>>> psycopg2.connect("postgresql://***:***@***:5432/postgres?sslmode=require")
<connection object at 0x40023af4c0; dsn: 'user=*** password=xxx dbname=postgres host=**** port=5432 sslmode=require', closed: 0>
```
Packet capture shows SNI

![image](https://user-images.githubusercontent.com/7516283/222022911-8fb2781b-0dd0-4f7f-bfa5-c21a6f2b29bb.png)

ARM64 (not working)

```
➜  docker run -it --rm --platform=linux/arm64/v8 python:3.11 /bin/bash
root@bb362a44779f:/# pip install psycopg2-binary
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.5-cp311-cp311-manylinux_2_24_aarch64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 11.6 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
root@bb362a44779f:/# python
Python 3.11.2 (main, Feb  9 2023, 20:14:21) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  psycopg2
>>> psycopg2.connect("postgresql://***:****@*****:5432/postgres?sslmode=require")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: SSL SYSCALL error: Success

>>>
```

Packet capture (does not include SNI)

![image](https://user-images.githubusercontent.com/7516283/222023530-bf5b3436-0dbb-43c8-b715-9e170c9f4460.png)

2: what you expected to happen

SNI present in Client Hello of TLS handshake. I believe this is the cause for the above error message.

3: what happened instead

SNI not present in Client Hello of TLS handshake on ARM build.

If possible, provide a script reproducing the issue.

```
FROM --platform=linux/arm64/v8 python:3.11

RUN pip install psycopg2-binary==2.9.5
```
Above: start python and connect to a database. Look at packets to see Server Name Indication. Probably has to do with packaged version of libpq, I am not sure.

**Comment by sjmiller609** [comment]
Also, I wanted to mention the error will only occur when the postgres server side is requiring server name indication

**Comment by dvarrazzo** [comment]
Psycopg just uses the libpq which uses the system openssl at the time of packaging.

Do you have the same problem if you install `psycopg2`, not the `-binary` version?

**Comment by sjmiller609** [comment]
Yes, I have the same error:

```
FROM --platform=linux/arm64/v8 python:3.11

RUN pip install psycopg2==2.9.5
```

```
➜  test-psycog docker run -it --rm test python
Python 3.11.3 (main, Apr 12 2023, 11:08:01) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  psycopg2
>>> psycopg2.connect("postgresql://postgres:******@org-coredb-inst-steven-4-14-23.data-1.use1.cdb-prod.com:5432?sslmode=require")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: SSL SYSCALL error: Success

```

**Comment by sjmiller609** [comment]
seems like it works with 2.9.6:

```
FROM --platform=linux/arm64/v8 python:3.11

RUN pip install psycopg2-binary==2.9.6
```

```
➜  test-psycog docker run -it --rm test python
Python 3.11.3 (main, Apr 12 2023, 11:08:01) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  psycopg2
>>> psycopg2.connect("postgresql://postgres:***@org-coredb-inst-steven-4-14-23.data-1.use1.cdb-prod.com:5432?sslmode=require")
<connection object at 0xffffb13bf4c0; dsn: 'user=postgres password=xxx host=org-coredb-inst-steven-4-14-23.data-1.use1.cdb-prod.com port=5432 sslmode=require', closed: 0>
```
