### ISSUE TITLE
AssertionError: database connection isn't set to UTC - Django==2.1.15, djangorestframework==3.9.0

### ISSUE THREAD

**Issue by maxi-89** [psycopg/psycopg2#1584]
**This is a bug tracker**
Traceback (most recent call last):
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/mixins.py", line 42, in list
    page = self.paginate_queryset(queryset)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/rest_framework/pagination.py", line 216, in paginate_queryset
    return list(self.page)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/core/paginator.py", line 143, in __len__
    return len(self.object_list)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/models/query.py", line 63, in __iter__
    for row in compiler.results_iter(results):
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1499, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1499, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/utils.py", line 96, in inner
    return func(*args, **kwargs)
  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC

**Please complete the following information:**
- OS: Linux Ubuntu
- Psycopg version: psycopg2-binary==2.8.6
- Python version: Python 3.9.15
- PostgreSQL version:psql (PostgreSQL) 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
- pip version pip 22.0.4 

**Describe the bug**

1: what you did
im having a problem when i try to get the year and month of an attribute (DatetimeField).
The query to my Db is like:
SELECT DISTINCT eventos_event.id, eventos_event.title, eventos_event.description,
                eventos_event.departamento_id, eventos_event.status, eventos_event.horario,
                eventos_event.ubicacion
FROM eventos_event
INNER JOIN eventos_assistance ON (eventos_event.id = eventos_assistance.evento_id)
WHERE (eventos_assistance.usuario_id = 591
       AND EXTRACT('month'
                   FROM eventos_event.horario AT TIME ZONE 'None') IN (5)
       AND EXTRACT('year'
                   FROM eventos_event.horario AT TIME ZONE 'None') IN (2023))
ORDER BY eventos_event.horario DESC
LIMIT 21

this is the filter that i code:
class EventAssistanceFilter(GenericFilter):

    def filter_queryset(self, request, queryset, view):
        query_param = 'going[]'
        going = request.query_params.getlist(query_param)

        if going:
            prefetch_related_objects(queryset, 'asistencias')
            filter_pks = list()
            for event in list(queryset):
                user_assistance = [assistance for assistance in event.asistencias.all()
                                   if assistance.usuario == request.user and str(assistance.asistencia) in going]
                if user_assistance:
                    filter_pks.append(event.pk)
            queryset = queryset.filter(pk__in=filter_pks)
        return super(EventAssistanceFilter, self).filter_queryset(request, queryset, view)

the timezone in my settings.py an postgrest DB is 'America/Argentina/Buenos_Aires' so whats the problem whit that?

### y tried to change this in my filter:
 
class EventAssistanceFilter(GenericFilter):

    def filter_queryset(self, request, queryset, view):
        query_param = 'going[]'
        going = request.query_params.getlist(query_param)

        **# Antes de ejecutar la consulta, establece el timezone en la conexión de la base de datos
        with connection.cursor() as cursor:
            cursor.execute("SET TIME ZONE 'America/Argentina/Buenos_Aires';")**

        if going:
            prefetch_related_objects(queryset, 'asistencias')
            filter_pks = list()
            for event in list(queryset):
                user_assistance = [assistance for assistance in event.asistencias.all()
                                   if assistance.usuario == request.user and str(assistance.asistencia) in going]
                if user_assistance:
                    filter_pks.append(event.pk)
            queryset = queryset.filter(pk__in=filter_pks)
        return super(EventAssistanceFilter, self).filter_queryset(request, queryset, view)

and i received this error: 

  File "/home/maximiliano/.pyenv/versions/virtual_3915_env/lib/python3.9/site-packages/django/db/backends/postgresql/utils.py", line 6, in utc_tzinfo_factory
    raise AssertionError("database connection isn't set to UTC")
AssertionError: database connection isn't set to UTC

the error is in this lines:

from django.utils.timezone import utc

def utc_tzinfo_factory(offset):
    if offset != 0:
        raise AssertionError("database connection isn't set to UTC")
    return utc

i found a similar issue here: https://github.com/psycopg/psycopg2/issues/1293#issuecomment-862835147, but im not sure if it is the same beacause im using:
Django==2.1.15
djangorestframework==3.9.0
psycopg2-binary==2.8.6

How can i solve this?

**Comment by dvarrazzo** [comment]
you should ask the Django project.
