### ISSUE TITLE
psycopg2  The error message does not match the actual situation

### ISSUE THREAD

**Issue by a984120978** [psycopg/psycopg2#1634]
**This is a bug tracker**
If you have a question, such has "how do you do X with Python/PostgreSQL/psycopg2" please [write to the mailing list](https://lists.postgresql.org/manage/) or [open a question](https://github.com/psycopg/psycopg2/discussions) instead.

**Please complete the following information:**
- OS:win11
- Psycopg version:2.9.9
- Python version:3.11
- PostgreSQL version:15.9
- pip version 22.1
- PC NAME: pc20070343

**Describe the bug**
Please let us know:
Another computer is connected normally 

I cannot connect to myself using PC20070343

conn = psycopg2.connect( host="pc20070343",  port="5432")
Traceback (most recent call last):
  File "C:\Users\Ot903056\PycharmProjects\PublicServer\test.py", line 4, in <module>
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ot903056\PycharmProjects\PublicServer\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 84: invalid continuation byte

BUT!
conn = psycopg2.connect( host="127.0.0.1",  port="5432")  Successfully connected!

conn = psycopg2.connect( host="locationhost",  port="5432")  # not input database

Traceback (most recent call last):
  File "C:\Users\Ot903056\PycharmProjects\PublicServer\test.py", line 4, in <module>
    conn = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Ot903056\PycharmProjects\PublicServer\venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 61: invalid continuation byte

The error message does not match the actual situation

**Comment by dvarrazzo** [comment]
What is the encoding of your database?

What happens if you connect with the same connection string using psycopg 3?

**Comment by a984120978** [comment]
UTF8,
Other computer links to pcname are normal
Local connection must be 127.0.0.1 or localhost

**Comment by dvarrazzo** [comment]
Sorry, apart from the encoding, I forgot to ask, what is the database language?

What happens if you repeat the same operations using psycopg 3? Or with psql, using the same connection string?

**Comment by a984120978** [comment]
pip install psycopg
ip = 'pc20070343'
engine = create_engine(f'postgresql+psycopg://{user}:{password}@{ip}:5432/big_data?client_encoding=utf8')
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) connection failed: :a879:f4a4:63c3:cebc), port 5432 failed: ��������:  û���������� "fe80::a879:f4a4:63c5:cebc%14", �û� "pc20070343", ���ݿ� "mcs", no encryption �� pg_hba.conf ��¼
(Background on this error at: https://sqlalche.me/e/20/e3q8)
change ip = 127.0.0.1'
**Successfully connected!**

**Comment by dvarrazzo** [comment]
@eayin2 thank you for confirming that the issue is fixed in psycopg 3.

Fixing the issue in psycopg2 is not trivial, so it will not be done, unless someone wants to fund for the development.

**Comment by Kevin0Jung** [comment]
hey dude, I got the same problem, and I solved it. Are you from China? If you create database with  **_Collate_** and **_Ctype_** in Chinese but not in `en_US.utf8 ` that will case the `UnicodeDecodeError`
![image](https://github.com/psycopg/psycopg2/assets/36042895/3461e9fc-f4a4-4491-b986-9282c6b3648e)

**Comment by Xiaoguangnihao** [comment]
> 嘿老兄，我也遇到了同样的问题，我已经解决了。你是从中国来的吗？如果您使用中文**_Collat​​​​e_**和**_Ctype_**创建数据库，但不是`en_US.utf8 `这样，则会`UnicodeDecodeError` ![图像](https://private-user-images.githubusercontent.com/36042895/318222510-3461e9fc-f4a4-4491-b986-9282c6b3648e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTU5NzAsIm5iZiI6MTcxNjM1NTY3MCwicGF0aCI6Ii8zNjA0Mjg5NS8zMTgyMjI1MTAtMzQ2MWU5ZmMtZjRhNC00NDkxLWI5ODYtOTI4MmM2YjM2NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA1Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWNjNWFiNjQxNmUwYTFhZDRhYzJiMWUzMWU5Y2E4MzQ3OGFlN2I5MjE5NGQzOGFmNGEzYTRkMDAxN2Q0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3g-N2RzoNt81mJh96oZfFoO3oJwlf8Lq8vSbHApwkg)

该如何处理啊

**Comment by Xiaoguangnihao** [comment]
> 嘿老兄，我也遇到了同样的问题，我已经解决了。你是从中国来的吗？如果你使用中文**_Collat​​​​​​e_**和**_Ctype_**创建数据库，但不是`en_US.utf8 `这样，屁股`UnicodeDecodeError` ![图像](https://private-user-images.githubusercontent.com/36042895/318222510-3461e9fc-f4a4-4491-b986-9282c6b3648e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTU5NzAsIm5iZiI6MTcxNjM1NTY3MCwicGF0aCI6Ii8zNjA0Mjg5NS8zMTgyMjI1MTAtMzQ2MWU5ZmMtZjRhNC00NDkxLWI5ODYtOTI4MmM2YjM2NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA1Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWNjNWFiNjQxNmUwYTFhZDRhYzJiMWUzMWU5Y2E4MzQ3OGFlN2I5MjE5NGQzOGFmNGEzYTRkMDAxN2Q0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3g-N2RzoNt81mJh96oZfFoO3oJwlf8Lq8vSbHApwkg)

如何处理呢？

**Comment by Kevin0Jung** [comment]
> > 嘿老兄，我也遇到了同样的问题，我已经解决了。你是从中国来的吗？如果你使用中文**_Collat​​​​​​e_**和**_Ctype_**创建数据库，但不是`en_US.utf8 `这样，屁股`UnicodeDecodeError` ![图像](https://private-user-images.githubusercontent.com/36042895/318222510-3461e9fc-f4a4-4491-b986-9282c6b3648e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTU5NzAsIm5iZiI6MTcxNjM1NTY3MCwicGF0aCI6Ii8zNjA0Mjg5NS8zMTgyMjI1MTAtMzQ2MWU5ZmMtZjRhNC00NDkxLWI5ODYtOTI4MmM2YjM2NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA1Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWNjNWFiNjQxNmUwYTFhZDRhYzJiMWUzMWU5Y2E4MzQ3OGFlN2I5MjE5NGQzOGFmNGEzYTRkMDAxN2Q0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3g-N2RzoNt81mJh96oZfFoO3oJwlf8Lq8vSbHApwkg)
> 
> 如何处理呢？

创建数据库时指定Collate and Ctype为en_US.utf8

**Comment by BaobaoAndDabao** [comment]
我是来自中国程序员 , 我尝试解决了这个问题, 只需要使用psycopg3作为后端数据库的驱动就可以解决这个问题:  
DATABASE_URL = (
    f"postgresql+psycopg://{config['username']}:{config['password']}@"
    f"{config['host']}:{config['port']}/{config['database']}"
)
# 创建 SQLAlchemy 引擎和会话
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()
# 解释:      f"postgresql+psycopg://{config['username']}:{config['password']}@" 中的 psycopg 代表使用 psycopg3

**Comment by infosec-ssk-dev** [comment]
solved for me after giving correct password for the user.

**Comment by Rojasoterom** [comment]
> solved for me after giving correct password for the user.

My god! Same to me here!! Thanks for this answer.

**Comment by SomaLily** [comment]
> > 嘿老兄，我也遇到了同样的问题，我已经解决了。你是从中国来的吗？如果你使用中文**_Collat​​​​​​e_**和**_Ctype_**创建数据库，但不是`en_US.utf8 `这样，屁股`UnicodeDecodeError` ![图像](https://private-user-images.githubusercontent.com/36042895/318222510-3461e9fc-f4a4-4491-b986-9282c6b3648e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTU5NzAsIm5iZiI6MTcxNjM1NTY3MCwicGF0aCI6Ii8zNjA0Mjg5NS8zMTgyMjI1MTAtMzQ2MWU5ZmMtZjRhNC00NDkxLWI5ODYtOTI4MmM2YjM2NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA1Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWNjNWFiNjQxNmUwYTFhZDRhYzJiMWUzMWU5Y2E4MzQ3OGFlN2I5MjE5NGQzOGFmNGEzYTRkMDAxN2Q0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3g-N2RzoNt81mJh96oZfFoO3oJwlf8Lq8vSbHApwkg)
> 
> 如何处理呢？

I had got a similar issue when query incloud 汉字。I think this is same problem in psycopg3/psycopg2, 汉字 not compatable between python and postgresql . So , query without any 汉字 the issue should be solved.

**Comment by dvarrazzo** [comment]
@SomaLily if you have a way to reproduce the issue in psycopg 3 I would be happy to fix it there. As written here previously, the issue is too complex to fix in psycopg2.

**Comment by dvarrazzo** [comment]
@SomaLily this query is problematic in psql too. The reason is that in the expression:
```
        CASE c.relkind 
            WHEN 'r' THEN '普通表'
            ELSE c.relkind
        END AS table_type,
```
the Chinese literal strings have no type, for Postgres they are of type unknown. The only known type in the operation is `c.relkind`, therefore the entire expression is cast to the `"char"` type, which doesn't support Unicode.

```
piro=# select pg_typeof(table_type) from (SELECT 
        n.nspname AS schema_name,
        c.relname AS table_name,
        CASE c.relkind 
            WHEN 'r' THEN '普通表'      
            WHEN 'v' THEN '视图'
            WHEN 'm' THEN '物化视图'
            WHEN 'i' THEN '索引'
            WHEN 'S' THEN '序列'
            WHEN 'f' THEN '外部表'
            WHEN 't' THEN '临时表'
            ELSE c.relkind      
        END AS table_type,
        pg_get_userbyid(c.relowner) AS owner,
        pg_size_pretty(pg_total_relation_size(c.oid)) AS size,
        obj_description(c.oid, 'pg_class') AS description
    FROM 
        pg_class c
    JOIN 
        pg_namespace n ON c.relnamespace = n.oid
    WHERE 
        n.nspname NOT IN ('pg_catalog', 'information_schema')
        AND c.relkind IN ('r', 'v', 'm', 'f', 't')
limit 1) x;
┌───────────┐
│ pg_typeof │
├───────────┤
│ "char"    │
└───────────┘
(1 row)
```

you can force the expression to be of type text by adding a cast on the first expression:

```
piro=# SELECT 
        n.nspname AS schema_name,
        c.relname AS table_name,
        CASE c.relkind 
            WHEN 'r' THEN '普通表'::text   -- cast here
            WHEN 'v' THEN '视图'
            WHEN 'm' THEN '物化视图'
            WHEN 'i' THEN '索引'
            WHEN 'S' THEN '序列'
            WHEN 'f' THEN '外部表'
            WHEN 't' THEN '临时表'
            ELSE c.relkind::text          -- and here
        END AS table_type,
        pg_get_userbyid(c.relowner) AS owner,
        pg_size_pretty(pg_total_relation_size(c.oid)) AS size,
        obj_description(c.oid, 'pg_class') AS description
    FROM 
        pg_class c
    JOIN 
        pg_namespace n ON c.relnamespace = n.oid
    WHERE 
        n.nspname NOT IN ('pg_catalog', 'information_schema')
        AND c.relkind IN ('r', 'v', 'm', 'f', 't')
limit 1;
┌─────────────┬──────────────────┬────────────┬───────┬────────────┬─────────────┐
│ schema_name │    table_name    │ table_type │ owner │    size    │ description │
├─────────────┼──────────────────┼────────────┼───────┼────────────┼─────────────┤
│ pg_toast    │ pg_toast_1234665 │ 临时表      │ piro  │ 8192 bytes │             │
└─────────────┴──────────────────┴────────────┴───────┴────────────┴─────────────┘
(1 row)
```

with these changes psycopg returns what I think is expected:

```
('pg_toast', 'pg_toast_1234665', '临时表', 'piro', '8192 bytes', None)
```

However I don't think this problem is related to the problem in this issue, which is about error messages requiring utf decoding on connection.

**Comment by chipmunkspd** [comment]
```
import psycopg2
import os

# Установите переменную окружения для кодировки
os.environ['PGCLIENTENCODING'] = 'UTF8'

# Параметры подключения
db_params = {
    'host': 'localhost',
    'database': 'Wrong_Database_Name',
    'user': 'postgres',
    'password': 'sedoc001',
    'port': '5432',
    'client_encoding': 'utf8'
}

# Подключение к базе данных
connection = None
try:
    connection = psycopg2.connect(**db_params)
    print("Подключение к базе данных успешно установлено")

    # Создание курсора для выполнения операций с базой данных
    cursor = connection.cursor()

    # Попробуйте выполнить запрос к конкретным столбцам
    cursor.execute("SELECT id, product_name::text FROM product LIMIT 1;")
    product = cursor.fetchone()
    print(product)

except (Exception, psycopg2.Error) as error:
    print("Ошибка при работе с PostgreSQL:", error)

finally:
    # Закрытие соединения
    if connection is not None:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")
```

The result of running this program gives a strange error!
D:\ISZF\py_projects\postgreSQL\venv\Scripts\python.exe D:\ISZF\py_projects\postgreSQL\list_tabels.py 
Ошибка при работе с PostgreSQL: 'utf-8' codec can't decode byte 0xc2 in position 61: invalid continuation byte

Process finished with exit code 0

This is misinforming the users of the package!

The error is observed for both psycopg2-binary and pure psycopg2. I have Python version 3.12 and PostgreSQL version 42.7.8 installed. I use the jdbc driver and Windows 10.
