### ISSUE TITLE
Can't import on Pypy

### ISSUE THREAD

**Issue by BlueKnighter** [psycopg/psycopg2#1700]
2024-05-27 00:06:21 Traceback (most recent call last):
2024-05-27 00:06:21   File "/opt/odoo/odoo-17.0.post20240522/setup/odoo", line 5, in <module>
2024-05-27 00:06:21     import odoo
2024-05-27 00:06:21   File "/opt/pypy/lib/pypy3.10/site-packages/odoo/__init__.py", line 134, in <module>
2024-05-27 00:06:21     from . import modules
2024-05-27 00:06:21   File "/opt/pypy/lib/pypy3.10/site-packages/odoo/modules/__init__.py", line 8, in <module>
2024-05-27 00:06:21     from . import db, graph, loading, migration, module, registry, neutralize
2024-05-27 00:06:21   File "/opt/pypy/lib/pypy3.10/site-packages/odoo/modules/db.py", line 4, in <module>
2024-05-27 00:06:21     from psycopg2.extras import Json
2024-05-27 00:06:21   File "/opt/pypy/lib/pypy3.10/site-packages/psycopg2/__init__.py", line 51, in <module>
2024-05-27 00:06:21     from psycopg2._psycopg import (                     # noqa
2024-05-27 00:06:21 ImportError: /opt/pypy/lib/pypy3.10/site-packages/psycopg2/_psycopg.pypy310-pp73-x86_64-linux-gnu.so: undefined symbol: PyInterpreterState_Main

**Please complete the following information:**
- OS: Ubuntu 22.04 container (on Docker)
- Psycopg version: psycopg2==2.9.2
- Python version: pypy3.10-v7.3.16
- PostgreSQL version: 
- pip version 23.0.1

**Comment by dvarrazzo** [comment]
pypi is not supported by psycopg2.
