### ISSUE TITLE
Add Python 3.13 packages for Windows

### ISSUE THREAD

**Issue by dvarrazzo** [psycopg/psycopg2#1736]
Packages for other platforms already released: see #1692.

For Windows we need https://github.com/appveyor/ci/issues/3927

**Comment by muizz-IHT** [comment]
Exception has occurred: ImportError
DLL load failed while importing _psycopg: The specified module could not be found.
  File "C:\Users\Desktop\pg_connect.py", line 1, in <module>
    import psycopg2
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

I am using the latest version of python 3.13, on windows OS. so during my pip install psycopg2 the wheel build failed as i didn't install visual studio buildtools, once this was downloaded, the installation happened smoothly. But while running the code i am getting this error. Any help would be much appreciated!

Version of psycopg2 == 2.9.10

**Comment by Loparch** [comment]
I have the same problem as @muizz-IHT when I try to import psycopg2 on Python 3.13 (Windows OS).

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import psycopg2
  File "C:\Users\lorenzo.pardo\AppData\Local\Programs\Python\Python313\Lib\site-packages\psycopg2\__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
    ...<10 lines>...
    )
ImportError: DLL load failed while importing _psycopg: No se puede encontrar el módulo especificado.


Any help would be much appreciated!

**Comment by muizz-IHT** [comment]
Since Python 13 was just released in October, many library wheels and binaries haven’t been built yet. I tried using Python 12, which has been out for a year, and psycopg2 worked flawlessly. It’s also recommended to install Visual Studio Build Tools for C++ to ensure everything runs smoothly. 
[check the vsbuild installer here](https://aka.ms/vs/17/release/vs_buildtools.exe)

**Comment by ninabel** [comment]
I can't install psycopg2-binary for python 3.13 on Windows 10.

```
C:\WINDOWS\system32>python -m pip install psycopg2-binary
Collecting psycopg2-binary
  Using cached psycopg2-binary-2.9.10.tar.gz (385 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: psycopg2-binary
  Building wheel for psycopg2-binary (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for psycopg2-binary (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\psycopg2
      copying lib\errorcodes.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\errors.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\extensions.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\extras.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\pool.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\sql.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\tz.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_ipaddress.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_json.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\_range.py -> build\lib.win-amd64-cpython-313\psycopg2
      copying lib\__init__.py -> build\lib.win-amd64-cpython-313\psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2-binary
Failed to build psycopg2-binary
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psycopg2-binary)
```

I've tryed to install Microsoft Visual C++ but it doesn't help. I would like to have psycopg2-binary ready for use without reistalling OS.

**Comment by dvarrazzo** [comment]
@ninabel You are not required to reinstall OS. You can use Python 3.12 or move your project to psycopg 3.

**Comment by dvarrazzo** [comment]
Note: in psycopg 3 there is already support for Python 3.13 and it doesn't require appveyor, see https://github.com/psycopg/psycopg/pull/966.

I would like to backport the same procedure to drop the dependency on appveyor, which is never timely enough in introducing new Python versions.

**Comment by dvarrazzo** [comment]
Python 3.13 psycopg2-binary packages for Windows released. We don't depend on Appveyor anymore to build these packages.

**Comment by edgarrmondragon** [comment]
@emilhdiaz you probably need to run `poetry cache clear pypi --all`

**Comment by emilhdiaz** [comment]
Thanks @edgarrmondragon! That indeed cleared the issue on my Mac.
