### ISSUE TITLE
Autocommit mode and hanging connections with connection pools

### ISSUE THREAD

**Issue by krowbar** [psycopg/psycopg2#261]
Kind of an odd corner case but here goes (same seems to happen with python3.4 and 2.7), psycopg2 version 2.5.3:
```python
def test_context(sql):
    r = None
    with psycopg2.connect(database='****', user='****', application_name='context') as conn:
        conn.autocommit = True
        with conn.cursor() as curs:
            try:
                curs.execute(sql)
                r = curs.fetchone()
                conn.commit()
            except Exception as exc:
                print('Error')
    return(r)

def test_pool(sql):
    pool = psycopg2.pool.SimpleConnectionPool(database='****', user='****', application_name='pool', minconn=0, maxconn=2)
    conn = pool.getconn()
    conn.autocommit = True
    with conn.cursor() as curs:
        try:
            curs.execute(sql)
            r = curs.fetchone()
        except Exception as exc:
            raise
    return r
```
works fine where there is no error:
```python
test_context('SELECT pg_sleep(10)')
test_pool('SELECT pg_sleep(10)')
```
and checking in with pg_stat_activity shows a connection get created and destroyed.

but doing something that fails like:
```python
test_context('SELECT pg_sleep(10); SELECT acnapom')
test_pool('SELECT pg_sleep(10); SELECT asdfas')
```
test context() works fine, with pg_stat_activity showing the connection get created and destroyed but test_pool() leaves an entry in pg_stat_activity with an idle state.

Oddly enough, repeated calls with errors to the pool create a new connection and seem to remove the oldest hanging connection.  The hanging connection does not seem to count towards maxconn either by setting minconn=0, maxconn=1.

From the end of test_context() with debugging:
```python
...
[80759] pq_raise: PQresultErrorMessage: err=ERROR:  column "asd" does not exist
LINE 1: SELECT pg_sleep(10); SELECT asd
                                    ^

[80759] pq_raise: err2=column "asd" does not exist
LINE 1: SELECT pg_sleep(10); SELECT asd
                                    ^

[80759] pq_fetch: fetching done; check for critical errors
[80759] psyco_curs_execute: res = -1, pgres = 0x0
Error
[80759] psyco_curs_close: cursor at 0x8007dcd68 closed
[80759] psyco_conn_close: closing connection at 0x8007dcc78
[80759] conn_close: PQfinish called
[80759] psyco_conn_close: connection at 0x8007dcc78 closed
[80759] connection_dealloc: deleted connection object at 0x8007dcc78, refcnt = 0
[80759] cursor_dealloc: deleted cursor object at 0x8007dcd68, refcnt = 0
```
and from test_pool()
```python
...
[80759] pq_raise: PQresultErrorMessage: err=ERROR:  column "ajnbas" does not exist
LINE 1: SELECT pg_sleep(10); SELECT ajnbas
                                    ^

[80759] pq_raise: err2=column "ajnbas" does not exist
LINE 1: SELECT pg_sleep(10); SELECT ajnbas
                                    ^

[80759] pq_fetch: fetching done; check for critical errors
[80759] psyco_curs_execute: res = -1, pgres = 0x0
Error
[80759] psyco_curs_close: cursor at 0x801b9c6d8 closed
[80759] pq_abort: pgconn = 0x8028f2800, autocommit = 1, status = 1
[80759] pq_abort_locked: pgconn = 0x8028f2800, autocommit = 1, status = 1
[80759] pq_abort_locked: no transaction to abort
[80759] conn_close: PQfinish called
[80759] connection_dealloc: deleted connection object at 0x8007dcd68, refcnt = 0
[80759] cursor_dealloc: deleted cursor object at 0x8007dcc78, refcnt = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in test_pool2
psycopg2.ProgrammingError: column "ajnbas" does not exist
LINE 1: SELECT pg_sleep(10); SELECT ajnbas
```
Looking at the debug code, it looks like the pool case misses a call to  psyco_conn_close.
In async mode, every error leaves a one hanging connection, with the older ones not being removed.

Exiting the interpreter cleans everything up, but it could be a problem for long running scripts.

**Comment by dvarrazzo** [comment]
Will review it before next release

**Comment by dvarrazzo** [comment]
In your test_pool() you are missing a putconn() call. I don't see any bug here.
