### ISSUE TITLE
errorcodes.lookup is not thread-safe

### ISSUE THREAD

**Issue by florentx** [psycopg/psycopg2#382]
I noticed this bug occasionally during load tests.

I can reproduce it with a short script

```python
from imp import reload
from threading import Thread
from psycopg2 import errorcodes

# Increase if it does not fail with KeyError
MAX_CYCLES = 2000

def f(pg_code='40001'):
    errorcodes.lookup(pg_code)

for __ in xrange(MAX_CYCLES):
    reload(errorcodes)
    (t1, t2) = (Thread(target=f), Thread(target=f))
    (t1.start(), t2.start())
    (t1.join(), t2.join())
```

**Comment by florentx** [comment]
The error is:

```python

Exception in thread Thread-3308:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<string>", line 9, in f
  File "./eggs/psycopg2-2.6.1-py2.7-linux-x86_64.egg/psycopg2/errorcodes.py", line 38, in lookup
    return _cache[code]
KeyError: '40001'
```

**Comment by dvarrazzo** [comment]
Fixed, thank you for the report and the script to reproduce the issue.
