### ISSUE TITLE
ImportError: datetime initialization failed on centos+mod_wsgi+apache24+python3.5

### ISSUE THREAD

**Issue by kwatog** [psycopg/psycopg2#404]
I hit the error below whenever I deploy 

```
 Loading WSGI script '/home/mkt/src/market/wsgi.py'.
    [wsgi:error] [pid 7828] mod_wsgi (pid=7828): Target WSGI script '/home/mkt/src/market/wsgi.py' cannot be loaded as Python module.
    [wsgi:error] [pid 7828] mod_wsgi (pid=7828): Exception occurred processing WSGI script '/home/mkt/src/market/wsgi.py'.
    [wsgi:error] [pid 7828] Traceback (most recent call last):
    [wsgi:error] [pid 7828]   File "/home/mkt/mktve/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 20, in 
    [wsgi:error] [pid 7828]     import psycopg2 as Database
    [wsgi:error] [pid 7828]   File "/home/mkt/mktve/lib/python3.5/site-packages/psycopg2/__init__.py", line 50, in 
    [wsgi:error] [pid 7828]     from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
    [wsgi:error] [pid 7828] ImportError: datetime initialization failed
    [wsgi:error] [pid 7828] 

```
Environment
```
  CentOS 6
    Apache/2.4.6 
    Python 3.5.1 on virtualenv
    postgresql-libs-8.4.20-4.el6_7.x86_64

```
Apache Config
```
    Alias /static /home/mkt/src/market/static
    WSGIScriptAlias / /home/mkt/src/market/wsgi.py
    WSGIDaemonProcess mysite.com python-path=/home/mkt/src:/home/mkt/mktve/lib/python3.5/site-packages user=myuser group=myuser
    WSGIProcessGroup  mysite.com



<Directory /home/mkt/src/market/static>
    Require all granted
    #Allow from All
</Directory>
<Directory /home/mkt/src/market>
    <Files wsgi.py>
        Require all granted
        #Satisfy Any
        #Allow from All
    </Files>
</Directory>
LogLevel info

```
to be fair, I'm not sure if mod_wsgi or psycopg2 is having problem. but if I use sqlite, I do not encounter the problem.

**Comment by dvarrazzo** [comment]
psycopg2 needs datetime. If it cannot be initialized it is because the environment set up by mod_wsgi.
