### ISSUE TITLE
732ea90 Fails to build in 32 bit environment on Windows

### ISSUE THREAD

**Issue by voltagex** [psycopg/psycopg2#422]
```
[00:01:30] %CMD_IN_ENV% python setup.py build
[00:01:30] Using default MSVC build environment for 32 bit architecture
[00:01:30] Executing: python setup.py build
[00:01:31] running build
[00:01:31] running build_py
[00:01:31] creating build
[00:01:31] creating build\lib.win32-3.5
[00:01:31] creating build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\errorcodes.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\extensions.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\extras.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\pool.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\psycopg1.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\tz.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\_json.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\_range.py -> build\lib.win32-3.5\psycopg2
[00:01:31] copying lib\__init__.py -> build\lib.win32-3.5\psycopg2
[00:01:31] creating build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\dbapi20_tpc.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\testconfig.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\testutils.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_async.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_bugX000.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_bug_gc.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_cancel.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_connection.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_copy.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_cursor.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_dates.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_errcodes.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_extras_dictcursor.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_green.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_lobject.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_module.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_notify.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_psycopg2_dbapi20.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_quote.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_transaction.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_types_basic.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_types_extras.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\test_with.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] copying tests\__init__.py -> build\lib.win32-3.5\psycopg2\tests
[00:01:31] Skipping optional fixer: buffer
[00:01:31] Skipping optional fixer: idioms
[00:01:31] Skipping optional fixer: set_literal
[00:01:31] Skipping optional fixer: ws_comma
[00:01:38] running build_ext
[00:01:38] Traceback (most recent call last):
[00:01:38]   File "setup.py", line 623, in <module>
[00:01:38]     ext_modules=ext)
[00:01:38]   File "C:\Python35\lib\distutils\core.py", line 148, in setup
[00:01:38]     dist.run_commands()
[00:01:38]   File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
[00:01:38]     self.run_command(cmd)
[00:01:38]   File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
[00:01:38]     cmd_obj.run()
[00:01:38]   File "C:\Python35\lib\distutils\command\build.py", line 135, in run
[00:01:38]     self.run_command(cmd_name)
[00:01:38]   File "C:\Python35\lib\distutils\cmd.py", line 313, in run_command
[00:01:38]     self.distribution.run_command(command)
[00:01:38]   File "C:\Python35\lib\distutils\dist.py", line 973, in run_command
[00:01:38]     cmd_obj.ensure_finalized()
[00:01:38]   File "C:\Python35\lib\distutils\cmd.py", line 107, in ensure_finalized
[00:01:38]     self.finalize_options()
[00:01:38]   File "setup.py", line 450, in finalize_options
[00:01:38]     getattr(self, "finalize_" + sys.platform)()
[00:01:38]   File "setup.py", line 354, in finalize_win32
[00:01:38]     self.libraries.remove("pq")
[00:01:38] ValueError: list.remove(x): x not in list
[00:01:38] Command exited with code 1
```

Full build log is at https://ci.appveyor.com/project/voltagex/python-appveyor-psycopg2/build/1.0.12/job/mfy2qc78wwcge0g7

**Comment by dvarrazzo** [comment]
Can you try now?

**Comment by voltagex** [comment]
I've just restored the repo from backup and kicked off a build, but I just
realised it's an old version of the source. Anything else will have to wait
til the weekend.

https://ci.appveyor.com/project/voltagex/python-appveyor-psycopg2/build/1.0.23
