### ISSUE TITLE
Binaries insertion is broken for Postgresql 8.4 + standard_conforming_strings=on

### ISSUE THREAD

**Issue by nahuel** [psycopg/psycopg2#430]
binary quoting seems to be broken when using Postgres 8.4 when the `standard_conforming_strings` variables is set to `on`, using Postgres 9.1 worked ok. To reproduce use the following 8.4 / 9.1 docker images:

```
docker run --name pg9.1 -e POSTGRES_PASSWORD=xx -p 7000:5432 -d postgres:9.1 
docker run --name pg8.4 -e POSTGRESQL_USER=postgres -e POSTGRESQL_PASS=xx -e POSTGRESQL_DB=postgres -p 7001:5432 -d nahuel/postgresql-8.4
```

then run the following script:

```python
#!/usr/bin/python

import psycopg2

DSN="dbname=postgres user=postgres password=xx port=%d host=localhost"

def insert():
    sql = "INSERT INTO t (c) VALUES (%s)"
    bin = psycopg2.Binary("\x00")
    
    print c.mogrify(sql, (bin, ))
    c.execute(sql, (bin, ))
    print "OK"
    
print psycopg2.__version__

for port in (7000,7001):
    db = psycopg2.connect(DSN % port)
    db.set_client_encoding("UTF8")
    c = db.cursor()
    c.execute('SELECT version()')
    print c.fetchone()
    c.execute("CREATE TABLE t (c BYTEA)")

    c.execute("SET standard_conforming_strings='off'")
    insert()
    c.execute("SET standard_conforming_strings='on'")
    insert() # fails with PG 8.4
    
    print
    print
```

You will get the following output:

```
2.6.1 (dt dec mx pq3 ext lo64)
('PostgreSQL 9.1.22 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit',)
INSERT INTO t (c) VALUES ('\\x00'::bytea)
OK
INSERT INTO t (c) VALUES ('\x00'::bytea)
OK


('PostgreSQL 8.4.22 on x86_64-unknown-linux-gnu, compiled by GCC gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit',)
INSERT INTO t (c) VALUES (E'\\000'::bytea)
OK
INSERT INTO t (c) VALUES (E'\000'::bytea)
Traceback (most recent call last):
  File "./test.py", line 28, in <module>
    insert() # fails with PG 8.4
  File "./test.py", line 12, in insert
    c.execute(sql, (bin, ))
psycopg2.DataError: invalid byte sequence for encoding "SQL_ASCII": 0x00
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
```

**Comment by nahuel** [comment]
Forgot to say psycopg2 is using `libpq5` version `9.4.6-0ubuntu0.15.10`

**Comment by dvarrazzo** [comment]
Psycopg doesn't really track standard_conforming_string: see issue #366. The value is read at connection time and not updated if it's changed in the server.

Does binary insertion work if the connection doesn't change its `standard_conforming_string` status? You can use the `options` parameter of the connection string to test, creating connections that already have the desired value so that psycopg can read it at connection time:

```python
>>> import psycopg2

>>> cnn = psycopg2.connect("options='-c standard_conforming_strings=off'")
>>> cur = cnn.cursor()
>>> cur.mogrify('select %s', ["ciao"])
"select E'ciao'"

>>> cnn = psycopg2.connect("options='-c standard_conforming_strings=on'")
>>> cur = cnn.cursor()
>>> cur.mogrify('select %s', ["ciao"])
"select 'ciao'"
```

**Comment by nahuel** [comment]
thanks, adding `options='-c standard_conforming_strings=on'` fixes this example.
