### ISSUE TITLE
No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by bvn13** [psycopg/psycopg2#439]
Where is this module? 

Windows 7 x64

`> python manage.py makemigrations
Traceback (most recent call last):
  File "C:\Users\bvn13\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\backends\postgresql\base.py", line 20, in <module>
    import psycopg2 as Database
  File "C:\Users\bvn13\AppData\Local\Programs\Python\Python35-32\lib\site-packages\psycopg2-2.6.1-py3.5-win32.egg\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: No module named 'psycopg2._psycopg'`

**Comment by bvn13** [comment]
When I installed psycopg2-2.6.1-cp35-cp35m-win32.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/
I have no error.

**Comment by dvarrazzo** [comment]
I'm sorry but I don't have a clue about how psycopg was installed in your system.
