### ISSUE TITLE
For builds from git master, what should the version number be?

### ISSUE THREAD

**Issue by voltagex** [psycopg/psycopg2#450]
This is technically not a pyscopg2 problem but I'm hoping you can advise. 
How is the version number set when building for release?

See: https://ci.appveyor.com/project/voltagex/python-appveyor-psycopg2/build/job/emxjpemwgl5mvr6b

```
Copying psycopg2.egg-info to build\bdist.win32\msi\Lib\site-packages\psycopg2-2.7.dev0-py3.5.egg-info
running install_scripts
Traceback (most recent call last):
  File "setup.py", line 624, in <module>
    ext_modules=ext)
  File "C:\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python35\lib\distutils\command\bdist_msi.py", line 234, in run
    sversion = "%d.%d.%d" % StrictVersion(version).version
  File "C:\Python35\lib\distutils\version.py", line 40, in __init__
    self.parse(vstring)
  File "C:\Python35\lib\distutils\version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '2.7.dev0'
Command exited with code 1
```

**Comment by dvarrazzo** [comment]
I don't think I understand the question. You are building a package out of something not meant so... I guess you can clone psycopg and have a branch following master but setting an arbitrary version number of yours following the [StrictVersion format](https://www.python.org/dev/peps/pep-0386/). As far as official psycopg is concerned we would switch to 2.7 on release, then 2.7.1 etc, with possible 2.7b1 etc releases... but there is nothing in StrictVersion that can represent an unstable package, as master currently is.
