### ISSUE TITLE
Undefined symbol: PyMemoryView_Type

### ISSUE THREAD

**Issue by smparsons** [psycopg/psycopg2#493]
See the issue I posted on StackOverflow a little earlier: http://stackoverflow.com/questions/41002017/setting-up-pgadmin4-psycopg-error

Basically I was trying to setup PGAdmin4 on my Linux Mint environment, and this of course depends on psycopg2. Every time I would try to run pgAdmin4.py, psycopg2 would display the following traceback:

```
Traceback (most recent call last):
  File "./lib/python2.7/site-packages/pgadmin4/pgAdmin4.py", line 46, in <module>
    app = create_app()
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/__init__.py", line 241, in create_app
    driver.init_app(app)
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/__init__.py", line 40, in init_app
    DriverRegistry.load_drivers()
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/registry.py", line 88, in load_drivers
    module = import_module(module_name)
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/pgadmin4/pgadmin/utils/driver/psycopg2/__init__.py", line 23, in <module>
    import psycopg2
  File "/home/samuel/pgadmin4/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: /home/samuel/pgadmin4/lib/python2.7/site-packages/psycopg2/_psycopg.so: undefined symbol: PyMemoryView_Type
```

I really have no clue what to do at this point. How can I fix this issue? Doing research on Google didn't reveal anything, it seems like my issue is pretty unique. 

Let me know if you need me to provide more information.

**Comment by dvarrazzo** [comment]
It seems you have a python 2.6 or previous in the path or library path and your system is trying to link against that version, or that pgadmin is executing the wrong python interpreter.

**Comment by dvarrazzo** [comment]
the point is that the `memoryview` object, and hence `PyMemoryView_Type` symbol, seems it was introduced in Python 2.7, so I'm somewhat confident you have some bit of Python 2.6 in the way.

**Comment by smparsons** [comment]
Yep, that was exactly the problem. My system by default is configured to use Python 2.6. By typing the command `python2.7 ./lib/python2.7/site-packages/pgadmin4/pgAdmin4.py`, I can switch to using the Python 2.7 interpreter, and then it works just fine.

Thanks.
