### ISSUE TITLE
Support for unicode surrogates with surrogateencode

### ISSUE THREAD

**Issue by alanhamlett** [psycopg/psycopg2#586]
When executing an SQL statement containing surrogate characters, psycopg2 raises a `UnicodeEncodeError`. For ex:

```
>>> b'\xe5\xae\x9e\xe7\x8e\xb0'.encode('utf8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-5: surrogates not allowed
```

Instead, it should encode strings with `surrogateescape`:

```
>>> b'\xe5\xae\x9e\xe7\x8e\xb0'.encode('utf8', 'surrogateescape').decode('utf8')
'实现'
```

Found this issue using `SQLAlchemy==1.1.14` and `psycopg2==2.7.3.1`. Only an issue with Python 3.

Original traceback:

```
>>> user = User(name='\udce5\udcae\udc9e\udce7\udc8e\udcb0')
>>> db.session.add(user)
>>> db.session.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-5: surrogates not allowed
```

**Comment by dvarrazzo** [comment]
Python3? I believe not.

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b''.encode('utf8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'encode'
```

```
>>> b'\xe5\xae\x9e\xe7\x8e\xb0'.decode('utf8')
'实现'
```

You are using unicode wrong.

**Comment by dvarrazzo** [comment]
To further, looking at your input:

```
>>> print('\udce5\udcae\udc9e\udce7\udc8e\udcb0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce5' in position 0: surrogates not allowed
```

```
piro=# select U&'\dce5\dcae\dc9e\dce7\dc8e\dcb0';
ERROR:  invalid Unicode surrogate pair at or near "U&'\dce5\dcae\dc9e\dce7\dc8e\dcb0'"
LINE 1: select U&'\dce5\dcae\dc9e\dce7\dc8e\dcb0';
               ^
```

This is an invalid unicode sequence: it will explode everywhere. If you want to manipulate invalid unicode you should use bytea, or write your own adapter/typecaster for psycopg (and deal with the consequences elsewhere).

**Comment by alanhamlett** [comment]
Oops sorry about that, I should filter invalid unicode strings before passing them to SQLAlchemy.
