### ISSUE TITLE
target_session_attrs connection option

### ISSUE THREAD

**Issue by cuu508** [psycopg/psycopg2#669]
Does psycopg2 support `target_session_attrs` connection option? If not, is it planned?

I'm using PostgreSQL 10 and this works:

    psql -d "host=node1,node2 target_session_attrs=read-write"

But this does not:

```
>>> psycopg2.connect("host=node1,node2 target_session_attrs=read-write")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 129, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/home/user/.virtualenvs/venv/lib/python3.6/site-packages/psycopg2/extensions.py", line 155, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "target_session_attrs"
```

**Comment by cuu508** [comment]
Nevermind, had to reinstall psycopg2 after installing a newer libpq and now it works.
