### ISSUE TITLE
dsa_area could not attach to a segment that has been freed

### ISSUE THREAD

**Issue by DeoLeung** [psycopg/psycopg2#692]
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/tmp/handlers/__init__.py", line 172, in new_func
  File "/tmp/handlers/__init__.py", line 980, in new_func
  File "/tmp/handlers/graph.py", line 707, in post
  File "/tmp/handlers/graph.py", line 285, in process_config
  File "/tmp/api_packages/commuting.py", line 147, in graph_data
  File "/tmp/handlers/__init__.py", line 417, in extract_sa_new
  File "/tmp/handlers/__init__.py", line 336, in _execute_sa
  File "/usr/local/lib/python3.6/site-packages/aiopg/utils.py", line 70, in __await__
    resp = yield from self._coro
  File "/usr/local/lib/python3.6/site-packages/aiopg/sa/connection.py", line 110, in _execute
    yield from cursor.execute(str(compiled), post_processed_params[0])
  File "/usr/local/lib/python3.6/site-packages/aiopg/cursor.py", line 114, in execute
    yield from self._conn._poll(waiter, timeout)
  File "/usr/local/lib/python3.6/site-packages/aiopg/connection.py", line 238, in _poll
    yield from asyncio.wait_for(self._waiter, timeout, loop=self._loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/site-packages/aiopg/connection.py", line 135, in _ready
    state = self._conn.poll()
psycopg2.InternalError: dsa_area could not attach to a segment that has been freed
CONTEXT:  parallel worker
```

python==3.6.4
aiopg==0.13.2
psycopg2==2.7.3.2
sqlalchemy==1.2.1

using `Debian`, the code is built as docker using `python:3.6`

I encountered this problem, any suggestion? or is it just a pg problem?

**Comment by dvarrazzo** [comment]
Definitely a postgres problem.
