### ISSUE TITLE
psycopg2 + SQLAchemly  will be hang problem

### ISSUE THREAD

**Issue by houjibofa** [psycopg/psycopg2#703]
Hi, everyone

When we use the sqlachemly + Psycopg2, we encounter the hang problem.

The more information is in: 

https://groups.google.com/forum/#!topic/sqlalchemy/sRgvpjUkzPU

Through my analyze,   I think there is a invalid cursor in the connection seesion pool. But I cannot find the 

reason, may be sqlachemly connection problem, maybe our nova code problem ...

We have try any solutions to analyze it, but it seems to hard for me. Can anyone give some solutions, thanks.

```
------------------------------------------------------------------------------------------------------------
2018-04-24T11:20:50.257+08:00 localhost nova-conductor ERROR [pid:741] [MainThread] [tid:127830448] [exc_filters.py:330 _raise_for_remaining_DBAPIError] [req-979e672a-9579-4ee2-8c7b-98726410972a] DBAPIError exception wrapped from (psycopg2.ProgrammingError) execute cannot be used while an asynchronous query is underway [SQL: 'SELECT 1']
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters Traceback (most recent call last):
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters   File "/opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters     context)
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters   File "/opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters     cursor.execute(statement, parameters)
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters ProgrammingError: execute cannot be used while an asynchronous query is underway
2018-04-24 11:20:50.256 741 ERROR oslo_db.sqlalchemy.exc_filters
2018-04-24T11:20:50.258+08:00 localhost nova-conductor ERROR [pid:741] [MainThread] [tid:127830448] [base.py:1230 _safe_close_cursor] [req-979e672a-9579-4ee2-8c7b-98726410972a] Error closing cursor
2018-04-24 11:20:50.257 741 ERROR sqlalchemy.pool.QueuePool Traceback (most recent call last):
2018-04-24 11:20:50.257 741 ERROR sqlalchemy.pool.QueuePool   File "/opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1226, in _safe_close_cursor
2018-04-24 11:20:50.257 741 ERROR sqlalchemy.pool.QueuePool     cursor.close()
2018-04-24 11:20:50.257 741 ERROR sqlalchemy.pool.QueuePool ProgrammingError: close cannot be used while an asynchronous query is underway
2018-04-24 11:20:50.257 741 ERROR sqlalchemy.pool.QueuePool
```

**Comment by houjibofa** [comment]
we also add some log to find the execution process, some one like this:

`[29017] conn_connect: new green postgresql connection at 0x8e8eb60
[29017] jjs pq_execute: pg connection at 0x8e8eb60 OK query is SELECT 1 no_begin 0 async 0
[29017] jjs pq_execute: lock conn 0x8e8eb60 query SELECT 1
[29017] pq_begin_locked: pgconn = 0x8e8eb60, autocommit = 0, status = 1
[29017] pq_execute_command_locked: pgconn = 0x8e8eb60, query = BEGIN
[29017] jjs pq_execute_command_locked: enter psyco_green pgconn = 0x8e8eb60, query = BEGIN
[29017] jjs pq_execute_command_locked: fin if route pgconn = 0x8e8eb60, query = BEGIN
[29017] jjs pq_execute_command_locked: fin all pgconn = 0x8e8eb60, query = BEGIN
[29017] pq_execute: executing SYNC query: pgconn = 0x8e8eb60
[29017] jjs pq_execute: finish unlock conn 0x8e8eb60 query SELECT 1
[29017] jjs pq_execute: pg connection at 0x8e8eb60 OK query is SELECT XXXX no_begin 0 async 0
[29017] jjs pq_execute: lock conn 0x8e8eb60 query SELECT XXX
[29017] pq_begin_locked: pgconn = 0x8e8eb60, autocommit = 0, status = 2
[29017] pq_execute: executing SYNC query: pgconn = 0x8e8eb60
[29017] jjs pq_execute: finish unlock conn 0x8e8eb60 query SELECT  XXXX
[29017] jjs pq_execute: pg connection at 0x8e8eb60 OK query is UPDATE  XXXX no_begin 0 async 0
[29017] jjs pq_execute: lock conn 0x8e8eb60 query UPDATE services SET updated_at='2018-04-27T05:46:42.890220'::timestamp, report_count=51648, last_seen_up='2018-04-27T05:46:42.889801'::timestamp WHERE services.id = 232
[29017] pq_begin_locked: pgconn = 0x8e8eb60, autocommit = 0, status = 2
[29017] pq_execute: executing SYNC query: pgconn = 0x8e8eb60
[29017] jjs pq_execute: finish unlock conn 0x8e8eb60 query UPDATE  XXXXX
[29017] jjs pq_commit: lock pgconn = 0x8e8eb60, autocommit = 0, status = 2
[29017] pq_execute_command_locked: pgconn = 0x8e8eb60, query = COMMIT
[29017] jjs pq_execute_command_locked: **enter psyco_green pgconn** = 0x8e8eb60, query = COMMIT
[29017] jjs pq_abort: enter pgconn = 0x8e8eb60, autocommit = 0, status = 2`


Through the log, I find the connection is hang in the pg_abort function, through the previous log, the connection lock is not unlock.

But through this process, I think the update is OK ,the problem is occurs in the commit. And the code is fail in psyco_exec_green function:

 ` if (!(conn->async_cursor = PyWeakref_NewRef((PyObject*)conn, NULL))) {
        goto end;
    }`

**Comment by dvarrazzo** [comment]
I understand that this query is not asynchronous but psycopg is being used in "green mode" with eventlet or gevent, right?

**Comment by dvarrazzo** [comment]
(I think `close()` *shoud* be used during an asynchronous way...)

**Comment by houjibofa** [comment]
Thanks for your replying. 

We use the eventlet  with python for openstack nova component.

We have tried the close method to ensure close the hang connection. But,  however, because of the waiting lock, the close failed through the sqlachemly.

Now, we have veritfied the error code. The thread is coorrupted in the following code

`if (!(conn->async_cursor = PyWeakref_NewRef((PyObject*)conn, NULL)))`

I think the PyWeakref_NewRef function occures an exception, so the sqlachemly will get it and try roll_back the connection. But, this error cannot be caughted by psycopg2 program, so it will not unlock the mutex-lock which is got in the pq_commit function.

The more details stack is in followings:

`/lib/python2.7/site-packages/sqlalchemy/engine/default.py:**do_rollback**:420
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:_rollback_impl:669
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:_autorollback:792
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:_**handle_dbapi_exception**:1350
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:_execute_context:1155
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:_execute_clauseelement:1012
/lib/python2.7/site-packages/sqlalchemy/sql/elements.py:_execute_on_connection:323
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:execute:916
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:scalar:846
/lib/python2.7/site-packages/oslo_db/sqlalchemy/engines.py:_connect_ping_listener:72
/lib/python2.7/site-packages/sqlalchemy/event/attr.py:__call__:256
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:__init__:92
/lib/python2.7/site-packages/sqlalchemy/engine/base.py:contextual_connect:2062
/lib/python2.7/site-packages/sqlalchemy/orm/session.py:_connection_for_bind:334
/lib/python2.7/site-packages/sqlalchemy/orm/session.py:_connection_for_bind:910
/lib/python2.7/site-packages/sqlalchemy/orm/session.py:connection:905
/lib/python2.7/site-packages/sqlalchemy/orm/query.py:_connection_from_session:2740
/lib/python2.7/site-packages/sqlalchemy/orm/query.py:_execute_and_instances:2749
/lib/python2.7/site-packages/sqlalchemy/orm/query.py:__iter__:2736
/lib/python2.7/site-packages/sqlalchemy/orm/query.py:all:2588
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:instance_get_all_by_filters_sort:2406
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:wrapped:346
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:wrapper:245
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:instance_get_all_by_filters:2184
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:wrapped:346
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:wrapper:245
/lib/python2.7/site-packages/nova/db/api.py:instance_get_all_by_filters:734
/lib/python2.7/site-packages/nova/objects/instance.py:_get_by_filters_impl:1109
/lib/python2.7/site-packages/nova/db/sqlalchemy/api.py:wrapper:301
/lib/python2.7/site-packages/nova/objects/instance.py:get_by_filters:1121
/lib/python2.7/site-packages/oslo_versionedobjects/base.py:wrapper:181
/lib/python2.7/site-packages/nova/conductor/manager.py:_object_dispatch:87
/lib/python2.7/site-packages/nova/conductor/manager.py:object_class_action_versions:96
/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py:_do_dispatch:126
/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py:_dispatch:182
/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py:_dispatch_and_reply:137
/lib/python2.7/site-packages/oslo_messaging/dispatcher.py:run:59
/lib/python2.7/site-packages/futurist/_utils.py:run:44
/lib/python2.7/site-packages/futurist/_green.py:__call__:70
/lib/python2.7/site-packages/eventlet/greenpool.py:_spawn_n_impl:82
`

Through the nova stack., we can see the _handle_dbapi_exception and do_rollback function, so I think the rollback command is from sqlachemly.

What's more, we also all many Dprint logs in the psycopg2 to find the error, the detail informatin as follows:

`[48193]  pq_execute_command_locked: fin if route pgconn = 0x8d92350, query = BEGIN
[48193]  pq_execute_command_locked: fin all pgconn = 0x8d92350, query = BEGIN
[48193] pq_execute: executing SYNC query: pgconn = 0x8d92350
[48193] before py newref 0x8d92350
[48193] enter end 0x8d92350
[48193] finish end 0x8d92350
[48193] pq_execute: finish unlock conn 0x8d92350 query SELECT 1
[48193] pq_execute: pg connection at 0x8d92350 OK query is SELECT XXX no_begin 0 async 0
[48193] before lock pgconn = 0x8d92350, owner 0 __lock 0
[48193] **after lock pgconn = 0x8d92350, owner 48193 __lock 1 (get lock)**
[48193] pq_execute: lock conn 0x8d92350 query SELECT XXXX
[48193] pq_begin_locked: pgconn = 0x8d92350, autocommit = 0, status = 2
[48193] pq_execute: executing SYNC query: pgconn = 0x8d92350
[48193] **before py newref 0x8d92350 (befoe the PyWeakref_NewRef in psyco_exec_green function)**
[48193]  pq_abort: enter pgconn = 0x8d92350, autocommit = 0, status = 2
[48193]  before lock pgconn = 0x8d92350, owner 48193 __lock 1`

Through the log, there is a pq_abort call after pq_execute, and donot unlock the mutex-lock. So the problem is one thread will be call pthread_mutex_lock twice, so the thread is hang.

I'm not sure if my analyze whether right or not.  Pls check. Thanks.

The following things, I'll to check:

1) what the exception is ?

I will check the exception from sqlachemly, and analyze PyWeakref_NewRef happen . I'm confusing why this happen. Because this thing only happen after our pg_ctl promote command, before do that there is a floating IP moving from old primary to standby.

2)  If the PyWeakref_NewRef fail, how can we do

In my view, if the PyWeakref_NewRef fail, the psycopg2 will not get it and donot unlock the mutex-lock. But the sqlachemly can get the exception. What anything can we do in this scenes.

**Comment by dvarrazzo** [comment]
Thank you for the detailed analysis. I will look at the `PyWeakref_NewRef` failure and how it manages the lock badly. If you have any patch to fix the problems before we start working on it ourselves please let us know.

**Comment by houjibofa** [comment]
We've add more logs and found the following logs

[17950]  finish py newref 0x947d920, before send query, async_cursor 0x7b8d788
[17950]  finish send query, before psyco_wait, conn 0x947d920
[17950]  before have_wait_callback conn 0x947d920
[17950]  before PyObject_CallFunctionObjArgs conn 0x947d920, cb 0x16f2320
[17950] conn_poll: status = 2, conn 0x947d920
[17950] conn_poll: async_status = ASYNC_WRITE 0x947d920
[17950]  before EXC_IF_ASYNC_IN_PROGRESS conn 0x947d920, async_cursor 0x7b8d788 (sqlachemly catch the programming error)
[17950]  before EXC_IF_ASYNC_IN_PROGRESS conn 0x947d920, async_cursor 0x7b8d788(sqlachemly catch the programming error and do the rollback)
[17950]  pq_abort: enter pgconn = 0x947d920, autocommit = 0, status = 2
[17950]  before lock pgconn = 0x947d920, owner 17950 __lock 1

We see the code is failed in the conn_poll to wait for result( before because we use the connection id to grep the log, so not find it, I think we need add connection id information in the Dprintf to help analyze the problem).

Through the gdb, we get the following stack
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00002aeb5fba0d02 in _L_lock_791 () from /lib64/libpthread.so.0
#2  0x00002aeb5fba0c08 in __GI___pthread_mutex_lock (mutex=0x8632810) at pthread_mutex_lock.c:64
#3  0x00002aeb6b276e95 in pq_abort () from /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so
#4  0x00002aeb6b27f86e in psyco_conn_rollback () from /usr/lib64/python2.7/site-packages/psycopg2/_psycopg.so
#5  0x00002aeb5f8b1b50 in call_function (oparg=<optimized out>, pp_stack=0x7fff0e759a40) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4082
#6  PyEval_EvalFrameEx (
    f=f@entry=Frame 0x81b5520, for file /opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py, line 421, in **# do_rollback** (self=<PGDialect_psycopg2(_json_serializer=None, _json_deserializer=None, _ischema=None, encoding='utf-8', isolation_level=None, use_native_unicode=True, _type_memos=<WeakKeyDictionary(_remove=<function at remote 0x781b488>, data={<weakref at remote 0x7f2f368>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2ced0>) at remote 0x7f2ce90>}, <weakref at remote 0x8690fc8>: {'impl': <Integer at remote 0x854c950>, 23: None}, <weakref at remote 0x7f008e8>: {'impl': <Integer at remote 0x7f2c750>, 23: None}, <weakref at remote 0x7f2f3c0>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2cf50>) at remote 0x7f2cf10>}, <weakref at remote 0x8671158>: {25: None, 'impl': <Variant(_has_column_expression=False, _has_result_processor=False, mapping={'mysql': ...(truncated), throwflag=throwflag@entry=0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:2740
#7  0x00002aeb5f8b1ad0 in fast_function (nk=<optimized out>, na=2, n=2, pp_stack=0x7fff0e759ba0, func=<function at remote 0x34132a8>)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:4184
#8  call_function (oparg=<optimized out>, pp_stack=0x7fff0e759ba0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4119
#9  PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7dacdc0, for file /opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py, line 669, in **## _rollback_impl** (self=<Connection(engine=<Engine(engine=<...>, dialect=<PGDialect_psycopg2(_json_serializer=None, _json_deserializer=None, _ischema=None, encoding='utf-8', isolation_level=None, use_native_unicode=True, _type_memos=<WeakKeyDictionary(_remove=<function at remote 0x781b488>, data={<weakref at remote 0x7f2f368>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2ced0>) at remote 0x7f2ce90>}, <weakref at remote 0x8690fc8>: {'impl': <Integer at remote 0x854c950>, 23: None}, <weakref at remote 0x7f008e8>: {'impl': <Integer at remote 0x7f2c750>, 23: None}, <weakref at remote 0x7f2f3c0>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2cf50>) at remote 0x7f2cf10>}, <weakref at remote 0x8671158>: {25: None, 'impl': <Variant(_has_column_expression=False...(truncated), throwflag=throwflag@entry=0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:2740
#10 0x00002aeb5f8b332d in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>,
    argcount=argcount@entry=1, kws=0x7ead658, kwcount=0, defs=0x0, defcount=0, closure=closure@entry=0x0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:3330
#11 0x00002aeb5f8b19df in fast_function (nk=<optimized out>, na=1, n=1, pp_stack=0x7fff0e759da0, func=<function at remote 0x33c0140>)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:4194
#12 call_function (oparg=<optimized out>, pp_stack=0x7fff0e759da0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4119
#13 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7ead4d0, for file /opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py, line 792, in **## _autorollback** (self=<Connection(engine=<Engine(engine=<...>, dialect=<PGDialect_psycopg2(_json_serializer=None, _json_deserializer=None, _ischema=None, encoding='utf-8', isolation_level=None, use_native_unicode=True, _type_memos=<WeakKeyDictionary(_remove=<function at remote 0x781b488>, data={<weakref at remote 0x7f2f368>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2ced0>) at remote 0x7f2ce90>}, <weakref at remote 0x8690fc8>: {'impl': <Integer at remote 0x854c950>, 23: None}, <weakref at re---Type <return> to continue, or q <return> to quit---
mote 0x7f008e8>: {'impl': <Integer at remote 0x7f2c750>, 23: None}, <weakref at remote 0x7f2f3c0>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2cf50>) at remote 0x7f2cf10>}, <weakref at remote 0x8671158>: {25: None, 'impl': <Variant(_has_column_expression=False,...(truncated), throwflag=throwflag@entry=0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:2740
#14 0x00002aeb5f8b332d in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>,
    argcount=argcount@entry=1, kws=0x81adfc0, kwcount=0, defs=0x0, defcount=0, closure=closure@entry=0x0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:3330
#15 0x00002aeb5f8b19df in fast_function (nk=<optimized out>, na=1, n=1, pp_stack=0x7fff0e759fa0, func=<function at remote 0x33c0578>)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:4194
#16 call_function (oparg=<optimized out>, pp_stack=0x7fff0e759fa0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4119
#17 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x81addc0, for file /opt/cloud/services/nova/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py, line 1350, in ## **_handle_dbapi_exception** (self=<Connection(engine=<Engine(engine=<...>, dialect=<PGDialect_psycopg2(_json_serializer=None, _json_deserializer=None, _ischema=None, encoding='utf-8', isolation_level=None, use_native_unicode=True, _type_memos=<WeakKeyDictionary(_remove=<function at remote 0x781b488>, data={<weakref at remote 0x7f2f368>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2ced0>) at remote 0x7f2ce90>}, <weakref at remote 0x8690fc8>: {'impl': <Integer at remote 0x854c950>, 23: None}, <weakref at remote 0x7f008e8>: {'impl': <Integer at remote 0x7f2c750>, 23: None}, <weakref at remote 0x7f2f3c0>: {869: None, 'impl': <IPAddress(_has_column_expression=False, _has_result_processor=False, impl=<INET at remote 0x7f2cf50>) at remote 0x7f2cf10>}, <weakref at remote 0x8671158>: {25: None, 'impl': <Variant(_has_column_expres...(truncated), throwflag=throwflag@entry=0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:2740
#18 0x00002aeb5f8b332d in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=<optimized out>,
    argcount=argcount@entry=6, kws=0x850ec30, kwcount=0, defs=0x0, defcount=0, closure=closure@entry=0x0)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:3330
#19 0x00002aeb5f8b19df in fast_function (nk=<optimized out>, na=6, n=6, pp_stack=0x7fff0e75a1a0, func=<function at remote 0x33c0b90>)
    at /usr/src/debug/Python-2.7.5/Python/ceval.c:4194
#20 call_function (oparg=<optimized out>, pp_stack=0x7fff0e75a1a0) at /usr/src/debug/Python-2.7.5/Python/ceval.c:4119

Through the new log, I think it may be our code problem, may be our code use different coroutine  with the same connection . But  I  can't get the the coroutine id in the python with the connection id which in the psycopg2.

**Comment by jiajunsu** [comment]
We have found the reason, it's SQLAlchemy's bug, unrelated with psycopg2. Sorry for this misleading report.

https://groups.google.com/forum/#!searchin/sqlalchemy/jinrong$20cai%7Csort:date/sqlalchemy/sRgvpjUkzPU/3zIgo0V4AgAJ

**Comment by dvarrazzo** [comment]
Cool. If you also find a way to e.g. raise an exception instead of deadlocking that'd be appreciated anyway. In the meantime, closing this issue.
