### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-isp64o0y/textfsm/

### ISSUE THREAD

**Issue by aratiterralogic** [psycopg/psycopg2#772]
'm trying to install netmiko 2.2.2 in my virtual environment with pip, but gives python setup.py egg_info failed error.
I tried to install using following command:

 pip install netmiko==2.2.2
python -m pip install netmiko

I'm using python 3.6 on windows 7.
setuptools is updated.
How to solve this ?
even tried to clone netmiko from github..bt again same erroe showing.

 
python -m pip install netmiko or pip install netmiko==2.2.2
Requirement already satisfied: netmiko==2.2.2 in ./lib/python3.4/site-packages/netmiko-2.2.2-py3.4.egg
Collecting paramiko>=2.4.1 (from netmiko==2.2.2)
  Downloading https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl (193kB)
    100% |################################| 194kB 23.1MB/s 
Collecting scp>=0.10.0 (from netmiko==2.2.2)
  Downloading https://files.pythonhosted.org/packages/ef/8c/399c5ddffc8c1bd2593ee6c8937ed31f005dcfa0c591da149f7b4b993f14/scp-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: pyyaml in ./lib/python3.4/site-packages (from netmiko==2.2.2)
Collecting pyserial (from netmiko==2.2.2)
  Downloading https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
    100% |################################| 194kB 22.9MB/s 
Collecting textfsm (from netmiko==2.2.2)
  Downloading https://files.pythonhosted.org/packages/a1/0d/a1b490503545b3b4600b965eae5d44cc2b6ce27cfb44f4debc563dbb56d3/textfsm-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/textfsm.egg-info
    writing dependency_links to pip-egg-info/textfsm.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/textfsm.egg-info/top_level.txt
    writing pip-egg-info/textfsm.egg-info/PKG-INFO
    /auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-isp64o0y/textfsm/setup.py", line 50, in <module>
        'texttable', 'terminal'])
      File "/auto/iconatest/users/aratsing/pyats/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/auto/iconatest/users/aratsing/pyats/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/auto/iconatest/users/aratsing/pyats/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/auto/iconatest/users/aratsing/pyats/lib/python3.4/site-packages/setuptools/dist.py", line 67, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/auto/pysw/cel63/python/3.4.1/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
        lines = header.split('\n')
    TypeError: Type str doesn't support the buffer API
    
    ----------------------------------------
**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-isp64o0y/textfsm/**

**Comment by dvarrazzo** [comment]
This is not us

**Comment by aratiterralogic** [comment]
means???

**Comment by dvarrazzo** [comment]
That this is not the netmiko, it's another completely unrelated project.

**Comment by aratiterralogic** [comment]
okk...i want to install netmiko..what i have to do??

**Comment by fogzot** [comment]
Maybe ask the netmiko people? 

https://github.com/ktbyers/netmiko
