### ISSUE TITLE
C implementation for a Column type does not provide _asdict()

### ISSUE THREAD

**Issue by rnbdsh** [psycopg/psycopg2#907]
This breaks pgadmin4. Traced down to [commit "Added C implementation for a Column type"](https://github.com/psycopg/psycopg2/commit/b3b225a9da450ed11ffbe8a61ba28ca6b343af32), the commit before ["fix-copy-async-hangs"](https://github.com/psycopg/psycopg2/tree/e00c4e2a7fdc98ea016ebfcf2c9012b04a75a5fa) still works.

How to reproduce:
Works: `sudo pip install git+https://github.com/psycopg/psycopg2.git@e00c4e2a7fdc98ea016ebfcf2c9012b04a75a5fa --upgrade; pkill min4; pgadmin4&`
Doesn't work: `sudo pip install git+https://github.com/psycopg/psycopg2.git@b3b225a9da450ed11ffbe8a61ba28ca6b343af32 --upgrade; pkill min4; pgadmin4&`

System: Arch Linux, pgadmin4 from pacman

(Sorry for the multiple edits, accidentally pressed enter on entering a title, Would fix it myself but I'm bad at C)

Stack trace from pgadmin4 log:
```
2019-04-25 21:31:40,813: ERROR	flask.app:	'psycopg2.extensions.Column' object has no attribute '_asdict'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/pgadmin4/web/pgadmin/browser/utils.py", line 259, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/lib/pgadmin4/web/pgadmin/browser/utils.py", line 309, in children
    children.extend(module.get_nodes(*args, **kwargs))
  File "/usr/lib/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 127, in get_nodes
    in_recovery, wal_paused = recovery_state(conn, manager.version)
  File "/usr/lib/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 52, in recovery_state
    status, result = connection.execute_dict(recovery_check_sql)
  File "/usr/lib/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 1202, in execute_dict
    desc.to_dict() for desc in cur.ordered_description()
  File "/usr/lib/pgadmin4/web/pgadmin/utils/driver/psycopg2/connection.py", line 1202, in <listcomp>
    desc.to_dict() for desc in cur.ordered_description()
  File "/usr/lib/pgadmin4/web/pgadmin/utils/driver/psycopg2/cursor.py", line 94, in to_dict
    ores = OrderedDict(self.orig_col._asdict())
AttributeError: 'psycopg2.extensions.Column' object has no attribute '_asdict'
```

**Comment by dvarrazzo** [comment]
`_asdict` wasn't advertised as interface. You can work around it with two lines of Python. Won't fix.
